# Generated by Django 5.1.11 on 2025-08-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maya_sawa_v2_ai_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingtask",
            name="knowledge_citations",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="processingtask",
            name="knowledge_context",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="processingtask",
            name="knowledge_used",
            field=models.BooleanField(default=False),
        ),
    ]
